### PR TITLE
feat: [MJO-4] - Update Button Component and Storybook

### PR DESCRIPTION
**Pull request by arthur404dev**
Updated Button Component with New Variants utilizing the color palette provided by Design.

## Example:

image

### variants:	
- "default"
- "neutral"
- "ghost"
- "primary"
- "secondary"
- "accent"

### sizes:
- "sm"
- "md"
- "lg"

### outline:
- "boolean"

### CODE REVIEW

**Review by Wtheodoro — APPROVED** [review]

**Review by JCastro456 — APPROVED** [review]

**Review by kari-osk — COMMENTED** [review]
The component looks amazing. I can imagine this kind of complexity, but I'm learning a lot ... thanks, guys

**Comment by ghost** [comment]
The variants are great, specially the color palette contrast and the experiencie with storybook in dark mode.

**Review by JCastro456 — COMMENTED** [review]
A differentiated way to create variants to reuse them later and still create top documentation. I am very grateful for the learning that you have given me.

**Review by deniseschirmer — APPROVED** [review]
Very good!!

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
